const interest_suggestions = [
  "Art",
  "Books",
  "Anime",
  "Manga",
  "Cooking",
  "Dance",
  "Fashion",
  "Fitness",
  "Gaming",
  "Music",
  "Photography",
  "Sports",
  "Tech",
  "Travel",
  "Writing",
  "History",
  "Science",
  "Astronomy",
  "Astrology",
  "Blogging",
  "DIY",
  "Gardening",
  "Hiking",
  "Skating",
  "Yoga",
  "Meditation",
  "Podcasts",
  "Film",
  "Theater",
  "Painting",
  "Sculpting",
  "Graphic Design",
  "Illustration",
  "3D Modeling",
  "Interior Design",
  "Crafts",
  "Knitting",
  "Origami",
  "Calligraphy",
  "Puzzle Solving",
  "Board Games",
  "Card Games",
  "Comedy",
  "Languages",
  "Cultural Studies",
  "Philosophy",
  "Psychology",
  "Virtual Reality",
  "Artificial Intelligence",
  "Blockchain",
  "Entrepreneurship",
  "Finance",
  "Investing",
  "Marketing",
  "Public Speaking",
  "Environmentalism",
  "Volunteering",
  "Animal Welfare",
  "Coding",
  "Robotics",
  "Space Exploration",
  "Politics",
  "Economics",
  "Social Justice",
  "Esports",
  "Cosplay",
  "Journaling",
  "Self-Development",
  "Veganism",
  "Architecture",
  "Creative Writing",
  "Poetry",
  "Video Editing",
  "Vlogging",
  "Makeup",
  "Hair Styling",
  "Martial Arts",
  "Fishing",
  "Surfing",
  "Skateboarding",
  "Snowboarding",
  "Rock Climbing",
  "Camping",
  "Cycling",
  "Horse Riding",
  "Geography",
  "Geology",
  "Mythology",
  "Archaeology",
  "Urban Exploration",
  "Genealogy",
  "Wine Tasting",
  "Coffee Brewing",
  "Tea Culture",
  "Chess",
  "Magic Tricks",
  "Parkour",
  "Adventure Sports",
  "Skydiving",
  "Sailing",
  "Kite Surfing",
  "Scuba Diving",
  "Birdwatching",
  "Wildlife Conservation",
  "Sustainable Living",
  "Holistic Health",
  "Acupuncture",
  "Tattoo Art",
  "Collecting",
  "Antiquing",
  "Model Building",
  "LARPing (Live Action Role Play)",
].map((interest) => ({ label: interest, value: interest }));
export default interest_suggestions;
